name: cypress test and code quality checks with sonarcloud
on: 
  push:
    branches-ignore:
      - master
      - staging

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.0.0 
        with:
          build: npm run build
          start: npm start